### ISSUE TITLE
Parse Integration

### ISSUE THREAD

**Issue by wmdmark** [wmdmark/backbone-project-1#2]
### Purpose

For this phase of the project you'll learn:
- How to fetch data from an external API using Backbone.js (Parse in this case)
- How to organize your project code into multiple files
### Resources
- [Parse JavaScript Guide](https://parse.com/docs/js/guide)
### Part 1: Albums
- [x] [Signup](https://www.parse.com/signup) for a free Parse account
- [x] Create an _Album_ object/class in Parse (use the Add Class button in the [Parse admin](https://www.parse.com/apps/) for your app under Core > Data)
  - [x] Add a name, description and image field to the Album object
  - [x] Add a few sample albums using the Parse data editor
- [x] Create the Album List View
  - [x] Create a new Backbone View (e.g. `views/album-grid.js`)
  - [x] Create a new Handlebars Template (e.g. `views/templates/album-grid.hbs`)
  - [x] Create a new Stylesheet(e.g. `views/styles/album-grid.scss`)
- [x] Load and render the album data
  - [x] In your `index.html` file, instantiate and render the album grid view
  - [x] Use a Parse Query to fetch the album data and render each album in the grid view.
    - [x] Create an additional view, template and stylesheet for the albums that are rendered in the grid (e.g. `album-grid-item.js/hbs/scss`)
### Part 2: Album Details and Tracks

For this phase we'll be adding the ability to view each album using the full album view created in the original tutorial.

**Use a [Backbone Router](http://backbonejs.org/#Router) to create two "pages":**
1. One for listing all the albums (created in phase one). This route should be the home page.
2. One for viewing an individual album.
- [ ] Render the Album's Details  
  - [ ] Use a Backbone router parameter to pass the ID of the album your viewing in the URL
  - [ ] Use the ID from the route to fetch the proper album from parse
  - [ ] Render the album details in the header section of the view
- [ ] Render the Album's Tracks
  - [ ] Create a `Track` object in Parse and populate it with sample data for each album
    - [ ] You'll need at least the following fields: `number, name, description, album`. The `album` field should be setup as a [Pointer Column](https://www.dropbox.com/s/jk39bq9k6c5edw7/Screenshot%202015-10-05%2022.14.11.png?dl=0) to the `Album` object.
  - [ ] Modify your album view to fetch the tracks for the album using a relational query. Something like:
  
  ``` js
  var query = new Parse.Query(Track);
  query.equalTo("album", album);
  query.find({
    success: function(tracks) {
      // tracks now contains the tracks for album
    }
  });
  ```
  - [ ] Render the tracks in the album list
